# go run github.com/ipfs-force-community/venus-cluster/venus-sector-manager/cmd/buildplugin@latest --src-dir=./ --out-dir=./
name = "fsstore"
description = ""
kind = "ObjStore"
onInit = "OnInit"
onShutdown = ""
export = [
    {extPoint="Constructor", impl="Open"},
]
